# Generated by Django 4.0 on 2021-12-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='CNPJ',
            field=models.CharField(max_length=14),
        ),
    ]
