# Generated by Django 4.0 on 2021-12-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0002_alter_costumer_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='relatedTicket',
            field=models.ManyToManyField(related_name='relatedTicket', to='FinalProject.Ticket'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='CNPJ',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='zCode',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='schedule',
            field=models.DateTimeField(blank=True, default='2021-12-16'),
        ),
    ]
