# Generated by Django 4.0 on 2021-12-17 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0003_serviceorder_relatedticket_alter_costumer_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='relatedTicket',
        ),
    ]
