# Generated by Django 4.0 on 2021-12-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0004_remove_serviceorder_relatedticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='relatedTicket',
            field=models.ManyToManyField(related_name='relatedTicket', to='FinalProject.Ticket'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='schedule',
            field=models.DateTimeField(blank=True),
        ),
    ]
