# Generated by Django 4.0 on 2021-12-20 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0007_alter_ticket_enddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='client',
            new_name='costumer',
        ),
    ]
