# Generated by Django 4.0 on 2021-12-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0008_rename_client_ticket_costumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.JSONField(default='{}'),
        ),
    ]
