# Generated by Django 4.0 on 2022-01-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0015_alter_ticket_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketCostumer', to='FinalProject.costumer'),
        ),
    ]
