# Generated by Django 4.0 on 2022-01-02 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0019_equipment_costumer_equipment_notes_equipment_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='costumer',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='FinalProject.costumer'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='phoneOperator',
            field=models.CharField(choices=[('Algar', 'Algar'), ('Vivo', 'Vivo'), ('OI', 'OI'), ('Claro', 'Claro'), ('TIM', 'Tim')], max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Execution', 'Execution'), ('Stock', 'Stock'), ('Warrantly', 'Warrantly'), ('Out of Service', 'Out of Service'), ('Disabled', 'Disabled')], max_length=30),
        ),
    ]
