# Generated by Django 4.0 on 2022-01-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0020_product_producer_alter_equipment_costumer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='relatedSo',
            field=models.ManyToManyField(related_name='relatedServiceOrder', to='FinalProject.Product'),
        ),
    ]
