# Generated by Django 4.0 on 2022-01-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0021_equipment_relatedso'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(choices=[('Smart', 'Smart'), ('Premium', 'Premium'), ('Essential', 'Essential'), ('Video managment', 'Video managment'), ('Evolution', 'Evolution'), ('Silometria', 'Silometria'), ('OnBoard', 'OnBoard')], default='', max_length=50),
        ),
    ]
