# Generated by Django 4.0 on 2022-01-03 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0022_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='relatedEquipment',
            field=models.ManyToManyField(related_name='equipmentRelated', to='FinalProject.Equipment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='relatedTicket',
            field=models.ManyToManyField(related_name='ticketRelated', to='FinalProject.Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
                ('categorie', models.CharField(choices=[('Installation', 'Installation'), ('Tachograph', 'Tachograph'), ('Support', 'Support'), ('Customization', 'Customization'), ('Training', 'Training'), ('Access Administration', 'Access Adiministration')], max_length=50)),
                ('price', models.FloatField()),
                ('description', models.TextField(default='')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinalProject.user')),
            ],
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='relatedService',
            field=models.ManyToManyField(related_name='serviceRelated', to='FinalProject.Services'),
        ),
    ]
