# Generated by Django 4.0 on 2022-01-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0023_serviceorder_relatedequipment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='tittle',
        ),
    ]
