# Generated by Django 4.0 on 2022-01-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0024_rename_name_product_tittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tittle',
            new_name='name',
        ),
    ]
