# Generated by Django 4.0 on 2022-01-03 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0025_rename_tittle_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
