# Generated by Django 4.0 on 2022-01-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0026_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Open', 'In Progress'), ('Open', 'Waiting for response'), ('Open', 'Escaled'), ('Open', 'Closed')], max_length=255),
        ),
    ]
