# Generated by Django 4.0 on 2022-01-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0027_alter_ticket_comment_alter_ticket_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Waiting for response', 'Waiting for response'), ('Escaled', 'Escaled'), ('Closed', 'Closed')], max_length=255),
        ),
    ]
