# Generated by Django 4.0 on 2022-01-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0029_alter_ticket_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
