# Generated by Django 4.0 on 2022-01-05 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0030_alter_ticket_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='endDate',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
