# Generated by Django 4.0 on 2022-01-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0031_alter_ticket_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
