# Generated by Django 4.0 on 2022-01-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0032_alter_ticket_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='priority',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], max_length=255),
        ),
    ]
