# Generated by Django 4.0 on 2022-01-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0035_ticket_group_alter_ticket_actionmade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Waiting for response', 'Waiting for response'), ('Escaled', 'Escaled'), ('Closed', 'Closed')], default='Support', max_length=255),
        ),
    ]
