# Generated by Django 4.0 on 2022-01-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0037_alter_ticket_group_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='analyzedIten',
            field=models.CharField(choices=[('Antenna - GPS', 'Antenna - GSM'), ('Antena - GSM', 'Antena - GSM'), ('CAN', 'CAN'), ('Sim Card', 'Sim Card'), ('Equipment', 'Equipment'), ('Speed Sensor', 'Speed Sensor'), ('Rpm Sensor', 'Rpm Sensor')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
