# Generated by Django 4.0 on 2022-01-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0038_alter_ticket_analyzediten_alter_ticket_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='plataform',
            field=models.CharField(choices=[('App Wikidados', 'App Wikidados'), ('Dynamix', 'Dynamix'), ('Gconnect', 'GConnect'), ('Getrak', 'Getrak'), ('Vdoweb', 'Vdoweb'), ('CRM', 'CRM'), ('Passanger', 'Passanger')], default='', max_length=255),
        ),
    ]
