# Generated by Django 4.0 on 2022-01-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0039_ticket_score_alter_ticket_plataform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[('Low', 1), ('Medium', 2), ('High', 3), ('Urgent', 4)]),
        ),
    ]
