# Generated by Django 4.0 on 2022-01-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0042_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
