# Generated by Django 4.0 on 2022-01-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0043_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='comm',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='FinalProject.comment'),
        ),
    ]
