# Generated by Django 4.0 on 2022-01-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0045_remove_costumer_comm_costumer_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='comm',
            field=models.ManyToManyField(blank=True, default='', to='FinalProject.Comment'),
        ),
    ]
