# Generated by Django 4.0 on 2022-01-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0046_alter_costumer_comm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='comm',
        ),
        migrations.AddField(
            model_name='costumer',
            name='comments',
            field=models.ManyToManyField(default='', related_name='relatedCostumer', to='FinalProject.Comment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='comments',
            field=models.ManyToManyField(default='', related_name='relatedEquipments', to='FinalProject.Comment'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='relatedTicket',
            field=models.ManyToManyField(default='', related_name='relatedTicket', to='FinalProject.Ticket'),
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(default='', related_name='relatedProducts', to='FinalProject.Comment'),
        ),
        migrations.AddField(
            model_name='service',
            name='comments',
            field=models.ManyToManyField(default='', related_name='relatedServices', to='FinalProject.Comment'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='comments',
            field=models.ManyToManyField(default='', related_name='relatedServiceOrder', to='FinalProject.Comment'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.ManyToManyField(default='', related_name='relatedTicket', to='FinalProject.Comment'),
        ),
    ]
