# Generated by Django 4.0 on 2022-01-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0048_rename_clientname_costumer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='CNPJ',
            field=models.CharField(blank=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='comments',
            field=models.ManyToManyField(blank=True, default='', related_name='relatedCostumer', to='FinalProject.Comment'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='priority',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], max_length=255),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='comments',
            field=models.ManyToManyField(blank=True, default='', related_name='relatedEquipments', to='FinalProject.Comment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(blank=True, default='', related_name='relatedProducts', to='FinalProject.Comment'),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='comments',
            field=models.ManyToManyField(blank=True, default='', related_name='relatedServices', to='FinalProject.Comment'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='comments',
            field=models.ManyToManyField(blank=True, default='', related_name='relatedServiceOrder', to='FinalProject.Comment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='comments',
            field=models.ManyToManyField(blank=True, default='', related_name='relatedTicket', to='FinalProject.Comment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
    ]
