# Generated by Django 4.0 on 2022-01-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0049_alter_costumer_cnpj_alter_costumer_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='CNPJ',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='priority',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 2), (4, 4)], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 2), (4, 4)]),
        ),
    ]
