# Generated by Django 4.0 on 2022-01-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0055_alter_costumer_priority_alter_ticket_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='client',
            new_name='costumer',
        ),
        migrations.AlterField(
            model_name='costumer',
            name='priority',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='relatedEquipment',
            field=models.ManyToManyField(blank=True, related_name='equipmentRelated', to='FinalProject.Equipment'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], max_length=1),
        ),
    ]
