# Generated by Django 4.0 on 2022-01-24 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0056_rename_client_serviceorder_costumer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='comment',
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
