# Generated by Django 4.0 on 2022-01-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0057_remove_serviceorder_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='deliveryDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
