# Generated by Django 4.0 on 2022-02-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0058_serviceorder_deliverydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
