# Generated by Django 4.0.3 on 2022-03-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinalProject', '0060_remove_costumer_comments_user_costumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='costumer',
        ),
    ]
